apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console-zdb
    chart: spring-boot-0.1.0
    release: console-zdb-web
  name: console-zdb-web
  namespace: console
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: console-zdb
      release: console-zdb-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: console-zdb
        release: console-zdb-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: console-zdb-api
        image: registry.au-syd.bluemix.net/cloudzdb/console-zdb-web:2.0
        imagePullPolicy: Always
        name: spring-boot
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: zdb-system-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console-zdb
    chart: spring-boot-0.1.0
    release: console-zdb-web
  name: console-zdb-web
  namespace: console
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: console-zdb
    release: console-zdb-web
  sessionAffinity: None
  type: ClusterIP